title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
# Color scheme supports "light" (default) and "dark"
color_scheme: dark

url: https://patjas211.github.io/BeckhoffTest

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
