title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark

logo: "/assets/images/logo4.png"
aux_links:
  "Infosys":
    - "https://infosys.beckhoff.com/index_en.htm"
nav_enabled: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
url: https://infosys.beckhoff.com/index_en.htm

aux_links:
  Infosys: https://infosys.beckhoff.com/index_en.htm

