title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
color_scheme: dark

logo: "/assets/images/logo3.png"
aux_links:
  "Infosys":
    - "https://infosys.beckhoff.com/index_en.htm"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false
url: https://patjas211.github.io/BeckhoffTest

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

